from . import config_models
from . import client_question
from . import res_partner
from . import res_users
from . import field_attendance
from . import marketing_material
from . import visit
from . import weekly_plan
from . import sale_order
from . import account_payment
from . import account_move
from . import hr_expense
from . import stock_check
from . import sales_target
from . import daily_task
from . import project
